# AlmaLinux 10.2 single-node lab: controller and compute share one VM.
ClusterName=hpc_lab
SlurmctldHost=instance-20260923-104239(10.140.0.2)
SlurmUser=slurm
AuthType=auth/munge
CredType=cred/munge

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd

SelectType=select/cons_tres
SelectTypeParameters=CR_CPU_Memory

NodeName=instance-20260923-104239 NodeAddr=10.140.0.2 CPUs=2 Sockets=1 CoresPerSocket=1 ThreadsPerCore=2 RealMemory=3000 State=UNKNOWN
PartitionName=debug Nodes=instance-20260923-104239 Default=YES MaxTime=00:30:00 State=UP
